dist:  bionic

env:
  - PYTHON_VERSION=3.6 MARIADB_VERSION=10.5
  - PYTHON_VERSION=3.7 MARIADB_VERSION=10.5
  - PYTHON_VERSION=3.8 MARIADB_VERSION=10.5
  - PYTHON_VERSION=3.9 MARIADB_VERSION=10.5
  - PYTHON_VERSION=3.10-rc MARIADB_VERSION=10.5
  - PYTHON_VERSION=3.10-rc MARIADB_VERSION=10.6

services: docker

install: pip install --user flake8 pytest

script:
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  - mkdir -vp csv/{in,done} && cp tests/csv/*.csv csv/in/
  - docker-compose up --abort-on-container-exit --exit-code-from app
