os: linux

addons:
  hosts:
    - db

services:
  - mysql

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
before_install:
  - pip install flake8
  - cat tests/sql/*.sql | mysql -u root -v
  - cat sql/*.sql | mysql -u root -v BNPPF
install:
  - pip install -r requirements.txt
script:
  - flake8 *.py
  - python banking.py
