---
version: '3'
services:
  app:
    build:
      context: .
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.11}
        BUILD_DATE: ${BUILD_DATE:-N/A}
    image: myapp
    environment:
      DB_HOST: db
      DB_NAME: BNPPF
      DB_PORT: 3306
      DB_PASSWORD: mypassword
      DB_USER: myusername
      CSV_TODO: /app/csv/todo
      CSV_DONE: /app/csv/done
      CSV_ERROR: /app/csv/error
      LOOP: ${LOOP:-1}
    volumes:
      - ./csv:/app/csv
    depends_on:
      - db
  db:
    image: mariadb:${MARIADB_VERSION:-10.11}
    environment:
      MYSQL_DATABASE: BNPPF
      MYSQL_USER: myusername
      MYSQL_PASSWORD: mypassword
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_INITDB_SKIP_TZINFO: "yes"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro
