version: '3'
services:
  app:
    build:
      context: .
      args: 
        - PYTHON_VERSION=${PYTHON_VERSION:-3.8}
    image: myapp
    environment:
      WAIT_HOSTS: db:3306
    volumes:
      - ./csv:/app/csv
    command: ["python", "./banking.py"]
    depends_on:
      - db
  db:
    image: mariadb:${MARIADB_VERSION:-10.5}
    environment:
      MYSQL_DATABASE: "BNPPF"
      MYSQL_USER: "myusername"
      MYSQL_PASSWORD: "mypassword"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_INITDB_SKIP_TZINFO: "yes"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro
