version: '3'
services:
  app:
    build: .
    image: myapp
    environment:
      WAIT_HOSTS: db:3306
    volumes:
      - ./csv:/app/csv
    command: ["python", "./banking.py"]
    depends_on:
      - db
  db:
    image: mariadb:10.4
    environment:
      MYSQL_DATABASE: "BNPPF"
      MYSQL_USER: "myusername"
      MYSQL_PASSWORD: "mypassword"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro
