---
name: BNPPF Parser Main CI/CD Pipelines

on:
  push:
    branches: [main]
    paths-ignore: [README.md]
  pull_request:
    branches: [main]
    paths-ignore: [README.md]

defaults:
  run:
    shell: bash

permissions: read-all

jobs:
  syntax:
    name: Syntax
    uses: ./.github/workflows/syntax.yaml

  tests:
    name: Tests
    needs: [syntax]
    uses: ./.github/workflows/tests.yaml
    with:
      coverage_min: '95'

  tag_release:
    name: Create Tag & Release
    needs: [tests]
    permissions:
      contents: write
    uses: ./.github/workflows/tag_release.yaml
    with:
      dry_run: |-
        ${{
          github.event_name == 'pull_request' ||
          (
            github.event_name == 'push' &&
            github.ref != 'refs/heads/main'
          )
        }}
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
