---
name: BNPPF Parser Syntax Checks

on:
  workflow_call:

permissions: read-all

jobs:
  syntax:
    name: Syntax
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Commitlint
        uses: wagoid/commitlint-github-action@v5
        with:
          failOnWarnings: true

      - name: Run YAMLlint
        run: pip install --user yamllint && yamllint --strict .

      - name: Install PyLint And Flake8
        run: pip install pylint flake8

      - name: Run Flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 --select=E9,F63,F7,F82 --show-source --statistics .

          # Run Flake8 (The GitHub editor is 127 chars wide)
          flake8 --max-line-length=127 --statistics .

          # Exit-zero treats all complexity errors as warnings
          flake8 --exit-zero --max-complexity=10 .

      - name: Run PyLint
        id: pylint
        continue-on-error: true
        run: pylint ./src/app/*.py

      - name: PyLint Result
        run: |
          if [ "${{ steps.pylint.outcome }}" == "failure" ]
          then
            echo "::warning::BNPPF PyLint NOK 💀"
          else
            echo "::notice::BNPPF PyLint OK 🎉"
          fi
