---
name: BNPPF Parser Tests

on:
  workflow_call:

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - '3.10'
          - '3.11'
        mariadb:
          - '10.6'
          - '10.11'

    name: Python-${{ matrix.python }} - MariaDB-${{ matrix.mariadb}}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install Pytest
        run: pip install pytest

      - name: Run Unit Testing
        working-directory: tests/app
        env:
          PYTHONPATH: ../../src/app/
        run: ./bnppf_test.py

      - name: Run Integration Testing (Docker)
        run: |
          mkdir -vp csv/{todo,done,error}
          chmod 777 csv/{todo,done,error}
          cp ./tests/csv/*.csv ./csv/todo/
          PYTHON_VERSION=${{ matrix.python }} \
          MARIADB_VERSION=${{ matrix.mariadb}} \
          BUILD_DATE=$(date) \
          LOOP=0 \
          docker-compose up --abort-on-container-exit --exit-code-from app
