name: BNPPF Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8, 3.9, 3.10.0-rc.1]
        mariadb: [10.5]

    name: Python-${{ matrix.python }} - MariaDB-${{ matrix.mariadb}}
  
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run BNPPF parser application on Docker
      run: |
        mkdir -vp csv/{in,done}
        cp tests/csv/*.csv csv/in/
        [ ${{ matrix.python }} == "3.10.0-rc.1" ] && PYTHON_VERSION=3.10-rc || PYTHON_VERSION=${{ matrix.python }}
        PYTHON_VERSION=${PYTHON_VERSION} MARIADB_VERSION=${{ matrix.mariadb}} docker-compose up --abort-on-container-exit --exit-code-from app
