---
name: BNPPF Parser Tests

on:
  workflow_call:
    inputs:
      coverage_min:
        description: BNPPF code minimum coverage
        required: true
        type: string

permissions: read-all

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - '3.10'
          - '3.11'
        mariadb:
          - '10.6'
          - '10.11'

    name: Python-${{ matrix.python }} - MariaDB-${{ matrix.mariadb}}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install Pytest And Coverage
        run: pip install pytest coverage

      - name: Run Unit Testing
        working-directory: tests/app
        env:
          PYTHONPATH: ../../src/app/
        run: coverage run -m pytest

      - name: Check Coverage
        id: coverage
        continue-on-error: true
        working-directory: tests/app
        run: coverage report -m --fail-under ${{ inputs.coverage_min }} ../../src/app/bnppf.py

      - name: Coverage Result
        run: |
          if [ "${{ steps.coverage.outcome }}" == "failure" ]
          then
            echo "::warning::BNPPF code coverage NOK 💀 (<${{ inputs.coverage_min }}%)"
            exit 1
          else
            echo "::notice::BNPPF code coverage OK 🎉 (>${{ inputs.coverage_min }}%)"
          fi

      - name: Run Integration Testing (Docker)
        run: |
          mkdir -vp csv/{todo,done,error}
          chmod 777 csv/{todo,done,error}
          cp ./tests/csv/*.csv ./csv/todo/
          PYTHON_VERSION=${{ matrix.python }} \
          MARIADB_VERSION=${{ matrix.mariadb}} \
          BUILD_DATE=$(date) \
          LOOP=0 \
          docker-compose up --abort-on-container-exit --exit-code-from app
